modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-LizardDogo/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-lizard-dogo"
authors="BuiltBrokenModding"

[[mods]] #mandatory
modId="sbmlizarddoggo" #mandatory
version="2.0.0" #mandatory
displayName="SBM-LizardDoggo" #mandatory
description='''Tamable lizard that acts like a dog''' #mandatory

[[dependencies.sbmlizarddoggo]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmlizarddoggo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"