package com.builtbroken.lizarddoggo;

import java.util.Arrays;

import com.builtbroken.lizarddoggo.entity.EntityLizard;

import net.minecraft.util.ResourceLocation;
import net.minecraftforge.common.config.Config.Type;
import net.minecraftforge.common.config.ConfigManager;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.client.event.ConfigChangedEvent.OnConfigChangedEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.registry.EntityEntryBuilder;

/**
 * Created by Dark(DarkGuardsman, Robert) on 1/12/2019.
 */
@Mod(modid = LizardDoggo.DOMAIN, name = LizardDoggo.NAME, version = LizardDoggo.VERSION)
@Mod.EventBusSubscriber
public class LizardDoggo
{
    public static final String MAJOR_VERSION = "@MAJOR@";
    public static final String MINOR_VERSION = "@MINOR@";
    public static final String REVISION_VERSION = "@REVIS@";
    public static final String BUILD_VERSION = "@BUILD@";
    public static final String MC_VERSION = "@MC@";
    public static final String VERSION = MC_VERSION + "-" + MAJOR_VERSION + "." + MINOR_VERSION + "." + REVISION_VERSION + "." + BUILD_VERSION;

    public static final String DOMAIN = "sbmlizarddogo";
    public static final String NAME = "SBM-Lizard Doggo";

    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        ModMetadata meta = event.getModMetadata();

        meta.authorList = Arrays.asList(new String[]{"DarkCow", "M1W3ST", "bl4ckscor3"});
        meta.autogenerated = false;
        meta.description = "Simple mod that adds a pet lizard.";
        meta.modId = DOMAIN;
        meta.name = NAME;
        meta.version = VERSION;
        meta.url = "https://www.curseforge.com/minecraft/mc-mods/sbm-lizard-dogo";
    }

    @SubscribeEvent
    public static void registerEntity(RegistryEvent.Register<EntityEntry> event)
    {
        EntityEntryBuilder<EntityLizard> builder = EntityEntryBuilder.create();
        builder.name(DOMAIN + ":lizard");
        builder.id(new ResourceLocation(DOMAIN, "lizard"), 0);
        builder.tracker(128, 1, true);
        builder.entity(EntityLizard.class);
        builder.egg(0x116409, 0x644F10);
        //builder.spawn() TODO
        event.getRegistry().register(builder.build());
    }

    @SubscribeEvent
    public static void onConfigChaned(OnConfigChangedEvent event)
    {
        if(event.getModID().equals(DOMAIN))
            ConfigManager.sync(DOMAIN, Type.INSTANCE);
    }
}
